### ISSUE TITLE
不想开源的话，就不要开源罢，扭扭捏捏算怎么回事儿

### ISSUE THREAD

**Issue by whorusq** [eolinker/PHP-EOLINKER-API-Studio-Lite-5.0#18]
@eolinker 既然开源啦，至少开放的基本功能可以正常使用吧？！连基本的编辑、删除都不能用，一堆 js 报错，这就是你们对开源的态度？！
本来之前一直用的 2.x 版本，虽然功能不多，但是够用。
现在看到新版本，赶紧过来体验下，浪费几个小时居然不能用。
就冲这，可见你们的做事态度，谁还敢考虑你们的商业版？

**Comment by ThisIsAnAn** [comment]
非常同意，要是不愿意开源的话，就不要放出这些东西来恶心人
