### ISSUE TITLE
语言设置问题

### ISSUE THREAD

**Issue by zhshengchao** [eolinker/PHP-EOLINKER-API-Studio-Lite-5.0#4]
只有英文版吗？看配置里有汉化版的，为什么没有生效呢？

**Comment by quanqiang-li** [comment]
解决了吗,我也想知道如何切换到中文

**Comment by zhshengchao** [comment]
> 解决了吗,我也想知道如何切换到中文

没有，看他源码好像是有中文的

**Comment by eolinker** [comment]
目前我们只提供英文版的，如需要中文版的，可以试试我们线上产品或者独立部署产品

**Comment by abellee** [comment]
有个文件夹叫`scripts`，里面搜索`EN`，后面跟了一堆的英文的，改成`CN`，然后再搜索`CN`，看到后面有一堆中文的，改成`EN`。

**Comment by yelijing18** [comment]
#9

**Comment by beizhebing** [comment]
�有个文件夹叫scripts，里面搜索EN，后面跟了一堆的英文的，改成CN，然后再搜索CN，看到后面有一堆中文的，改成EN。  
虽然这样改成功了，但是这样发出来我内心还是有那么一丢丢的羞愧

**Comment by yoder** [comment]
> �有个文件夹叫scripts，里面搜索EN，后面跟了一堆的英文的，改成CN，然后再搜索CN，看到后面有一堆中文的，改成EN。
> 虽然这样改成功了，但是这样发出来我内心还是有那么一丢丢的羞愧

一样的处理方式
